# Generated by Django 3.2.13 on 2022-06-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(unique=True),
        ),
    ]
