# Generated by Django 4.0.4 on 2022-07-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_last_update_blog_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='show',
        ),
        migrations.AddField(
            model_name='blog',
            name='status_publish',
            field=models.CharField(choices=[('draft', 'draft'), ('publish', 'publish')], default='draft', max_length=7),
        ),
    ]
