# Generated by Django 4.0.5 on 2022-07-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='massage',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
