# Generated by Django 4.0.5 on 2022-07-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_massage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Blog',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='comment',
            name='massage',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
