# Generated by Django 4.1.3 on 2023-05-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_massage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='massage',
            field=models.TextField(null=True, unique_for_date=True),
        ),
    ]
